name: 构建SM8650-12内核

on:
  workflow_call:
  workflow_dispatch:
  
jobs:
  
  build:
    
    runs-on: ubuntu-latest

    steps:

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 16384
        temp-reserve-mb: 4096
        swap-size-mb: 8192
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'

    - name: Configure Git
      run: |
         git config --global user.name "Yxiguan"
         git config --global user.email "2501608779@qq.com"
    
    - name: 安装repo
      run: |
        curl https://storage.googleapis.com/git-repo-downloads/repo > ~/repo
        chmod a+x ~/repo
        sudo mv ~/repo /usr/local/bin/repo
    
    - name: 安装编译环境
      run: |
        sudo apt update && sudo apt upgrade -y
        sudo apt install curl git python3 -y

    - name: 拉取oneplus 12内核清单
      run: |
        mkdir kernel && cd kernel
        repo init -u https://github.com/OnePlusOSS/kernel_manifest.git -b oneplus/sm8650 -m oneplus12_v.xml --depth=1
        repo sync -j$(nproc --all)
        sed -i 's/export REPACK_IMG=true/export REPACK_IMG=false/Ig' kernel_platform/oplus/build/oplus_setup.sh
        sed -i 's/ -dirty$//' kernel_platform/common/scripts/setlocalversion
        sed -i 's/ -dirty$//' kernel_platform/msm-kernel/scripts/setlocalversion
        sed -i '1a CONFIG_LOCALVERSION="-XiGuan"' kernel_platform/common/arch/arm64/configs/gki_defconfig
        sed -i '1a CONFIG_LOCALVERSION="-XiGuan"' kernel_platform/msm-kernel/arch/arm64/configs/gki_defconfig
        # sed -i 's/BUILD_VENDOR_DLKM=1/BUILD_VENDOR_DLKM=0/; s/BUILD_INIT_BOOT_IMG=1/BUILD_INIT_BOOT_IMG=0/' kernel_platform/msm-kernel/build.config.msm.pineapple
        # sed -i 's/BUILD_SYSTEM_DLKM=1/BUILD_SYSTEM_DLKM=0/' kernel_platform/common/build.config.gki.aarch64

    - name: 添加KernelSU Next
      run: |
        cd kernel/kernel_platform/common
        curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next
        
    - name: 添加SUSFS
      run: |
           cd kernel
           git clone https://gitlab.com/simonpunk/susfs4ksu.git -b gki-android14-6.1
           git clone https://github.com/TheWildJames/kernel_patches.git
           cd kernel_platform
           cp ../susfs4ksu/kernel_patches/KernelSU/10_enable_susfs_for_ksu.patch ./common/KernelSU-Next/
           cp ../susfs4ksu/kernel_patches/50_add_susfs_in_gki-android14-6.1.patch ./common/
           cp ../susfs4ksu/kernel_patches/fs/* ./common/fs/
           cp ../susfs4ksu/kernel_patches/include/linux/* ./common/include/linux/
           cd ./common/KernelSU-Next
           patch -p1 --forward < 10_enable_susfs_for_ksu.patch || true
           cd ..
           patch -p1 < 50_add_susfs_in_gki-android14-6.1.patch || true
           cp ../../kernel_patches/69_hide_stuff.patch ./
           patch -p1 -F 3 < 69_hide_stuff.patch
           cp ../../kernel_patches/apk_sign.c_fix.patch ./
           patch -p1 -F 3 < apk_sign.c_fix.patch
           cp ../../kernel_patches/core_hook.c_fix.patch ./
           patch -p1 --fuzz=3 < ./core_hook.c_fix.patch
           cp ../../kernel_patches/selinux.c_fix.patch ./
           patch -p1 -F 3 < selinux.c_fix.patch
           
    - name: 编译内核
      run: |
        cd kernel
        # export  LTO=thin
        ./kernel_platform/oplus/build/oplus_build_kernel.sh pineapple gki
        
    - name: 打包 AnyKernel3
      run: |
       git clone https://github.com/Yxiguan/AnyKernel3.git --depth=1
       rm -rf ./AnyKernel3/.git
       sudo chmod 777 ./AnyKernel3/ksu.sh
       cd ./AnyKernel3/
       ./ksu.sh
       cd ..
       cp kernel/kernel_platform/out/msm-kernel-pineapple-gki/dist/Image ./AnyKernel3/
       
    - name: 上传 AnyKernel3
      uses: actions/upload-artifact@v4
      with:
        name: AnyKernel3_KernelSU_Next-For-12
        path: ./AnyKernel3/*

    - name: 上传 Image
      uses: actions/upload-artifact@v4
      with:
        name: Image-KernelSU_Next-SUSFS-12
        path: kernel/kernel_platform/out/msm-kernel-pineapple-gki/dist/Image
